var t=function(){function c(a,b){for(var c=0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}return function(a,b,e){b&&c(a.prototype,b);e&&c(a,e);return a}}();function y(c,a){if(!(c instanceof a))throw new TypeError("Cannot call a class as a function");}window.NodeList&&!NodeList.prototype.forEach&&(NodeList.prototype.forEach=function(c,a){a=a||window;for(var b=0;b<this.length;b++)c.call(a,this[b],b,this)});
OBR.c.mq={kq:1,lq:2,Wp:3,Vp:4,Up:5,$p:6,Xp:7,Yp:8,Zp:9,bq:10,aq:11,cq:12,fq:13,gq:14,eq:15};
OBR.Fd=OBR.Fd||function(){function c(){y(this,c);this.Fb=!0;this.sa=null;this.Od=OBR.c.Wc+"logger/v1/smartFeed/"}t(c,[{key:"init",value:function(a){if(!1!==this.Fb){OBR.g.log("SmartFeed Started");this.Fb=!1;if(!a)throw OBR.g.log("SmartFeed - Widget Data is null"),new TypeError("SmartFeed - Widget Data is null");var b=window.JSON.parse(a.f("feedContent","[]")),c=this.prepareJokerCards(b),b=b.filter(function(a){return"widget"===a.type});OBR.tm=new OBR.Rf({user:this,jokerCards:c,feedContent:b,feedCyclesLimit:a.f("feedCyclesLimit",
0),feedLoadChunkSize:a.f("feedLoadChunkSize",1)});this.sa=OBR.tm.init(a);this.Hj=!0===a.e("oo",!1);this.Gj=a.f("interactionLayerEnabled",!1);this._initInteractionLayer(a)}}},{key:"prepareJokerCards",value:function(a){a=a.filter(function(a){return"widget"!==a.type});var b={},c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];d&&(b[parseInt(d.pos,10)]=d)}return b}},{key:"_initInteractionLayer",value:function(a){!this.Hj&&this.Gj&&(this.Cq=new OBR.Da(a))}}]);return c}();
OBR.Rf=OBR.Rf||function(){function c(a){y(this,c);this.Fb=!0;this.vc=this.Fj=!1;this.ra=a.jokerCards||{};this.Eb=a.feedContent&&0===Object.keys(a.feedContent).length&&a.feedContent.constructor===Object?void 0:a.feedContent;this.Pd=-1;this.eg=0;this.gg=a.feedCyclesLimit?a.feedCyclesLimit:0;this.hg=a.feedLoadChunkSize&&!isNaN(a.feedLoadChunkSize)&&0<a.feedLoadChunkSize?a.feedLoadChunkSize:1;this.$=-1;a.currentWidget&&this.init(a.currentWidget)}t(c,[{key:"init",value:function(a){if(!1!==this.Fb&&(void 0!==
this.Eb||!a.Ge())){this.fg=a.e("wnid",null);this.Dj=a.e("abTestVal",null);this.jg=a.qe();this.lg=a.ie();this.dg=a.je();this.ig=a.pe();this.wc=a.r();a.Jh()&&(this.Eb=[{type:"widget",id:this.wc}]);OBR.g.log("InfiniteScroll Started");this.Fb=!1;var b=a.I();this.Qd=OBR.b.v(b);this.sa=OBR.b.createElement("div",null,null,{"class":"ob-smartfeed-wrapper"});this.Qd.parentNode.insertBefore(this.sa,this.Qd);this.sa.appendChild(this.Qd);var c=a.f("hideHeaders",!1);this.$+=1;a.Qi(this.$);OBR.display.Ra(this.afterRender.bind(this));
OBR.k.Ai(this.stopInfiniteScroll.bind(this));this.Ij=a.X();this.Ea=this.sa.firstChild;(this.Ej=c)&&OBR.b.K(".ob-smartfeed-wrapper .OUTBRAIN:not(:first-child) .ob-widget-header {display:none;}");OBR.b.K(".ob-smartfeed-wrapper .OUTBRAIN:not(:first-child) .ob_what {display:none;} .ob-smartfeed-joker {box-shadow: 0 2px 2px rgba(0,0,0,.28); margin-bottom: 20px; padding-bottom: 4px; padding-top: 0; background-color: #fff;}");0<this.Eb.length&&0<Object.keys(this.ra).length&&this.hideAllJokers();this.createLoaderObject();
this.fireLastWidgetExposeEvent(b);return this.sa}}},{key:"hideAllJokers",value:function(){for(var a in this.ra)if(this.ra.hasOwnProperty(a)){var b=this.ra[a];b&&b.selector&&(b=document.querySelector(b.selector))&&(b.style.display="none")}}},{key:"createWidgetContainer",value:function(){if(!this.vc){this.kg=this.Ea;this.$+=1;var a={"class":"OUTBRAIN","data-src":this.Ij,"data-widget-id":this.wc,"data-feed-idx":this.$,"data-feed-father-id":this.fg,"data-feed-father-AB":this.Dj};this.jg&&(a["data-ob-installation-type"]=
this.jg);this.lg&&(a["data-ob-user-id"]=this.lg);this.dg&&(a["data-ob-app-ver"]=this.dg);this.ig&&(a["data-ob-installation-key"]=this.ig);this.Ea=OBR.b.createElement("div",null,null,a);this.sa.appendChild(this.Ea);OBR.$a.Kj([this.Ea])}}},{key:"createJokerContainer",value:function(a){var b;this.kg=this.Ea;this.Ea=OBR.b.createElement("div",null,null,{"class":"ob-smartfeed-"+a.type.toLowerCase(),"data-feed-idx":this.$,"data-feed-father-id":this.fg});"joker"===a.type?(b=document.querySelector(a.selector),
null!==b?(b.parentNode.removeChild(b),b.style.display="block"):OBR.g.log("joker failed - "+a.selector)):"adJoker"===a.type&&("dfp"===a.adType.toLowerCase()?b=this.createDFPAd(a):"adsense"===a.adType.toLowerCase()&&(b=this.createAdSense(a)));this.Ea.appendChild(b);this.sa.appendChild(this.Ea)}},{key:"createDFPAd",value:function(a){try{var b=OBR.b.createElement("div","ad-unit",null,null),c=OBR.b.createElement("script",null,null,{src:"//securepubads.g.doubleclick.net/static/glade.js",async:"true"}),
d=OBR.b.createElement("div",null,null,{"data-glade":"","data-ad-unit-path":a.adPath,"data-json":a.adData||"",width:a.adWidth,height:a.adHeight});b.appendChild(d);b.appendChild(c);return b}catch(f){}}},{key:"createAdSense",value:function(a){try{var b=OBR.b.createElement("div","ad-unit",null,null),c=OBR.b.createElement("script",null,null,{src:"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",async:"true"}),d=OBR.b.createElement("ins",null,"display:inline-block;width:100%;height:200px",{"class":"ob-smartfeed-adjoker adsbygoogle",
"data-ad-client":a.adClient,"data-ad-slot":a.adSlot}),f=OBR.b.createElement("script",null,null,null);f.innerText="googletag.cmd.push(function() {googletag.display('ad-unit');})";this.kg=this.Ea;b.appendChild(c);b.appendChild(d);b.appendChild(f);return b}catch(h){}}},{key:"createLoaderObject",value:function(){this.Gb=OBR.b.createElement("div",null,null,{"class":"ob_sf_loader"});this.Gb.innerHTML='<div class="bounce1"></div><div class="bounce2"></div><div class="bounce3"></div>';OBR.b.K(".ob_sf_loader {margin: 25px auto 20px; width: 70px; text-align: center;} .ob_sf_loader > div {width: 18px; height: 18px; background-color: #333; border-radius: 100%; display: inline-block;  -webkit-animation: sk-bouncedelay 1.4s infinite ease-in-out both; animation: sk-bouncedelay 1.4s infinite ease-in-out both; }  .ob_sf_loader .bounce1 { -webkit-animation-delay: -0.32s;  animation-delay: -0.32s;  } .ob_sf_loader .bounce2 { -webkit-animation-delay: -0.16s;  animation-delay: -0.16s; }  @-webkit-keyframes sk-bouncedelay { 0%, 80%, 100% { -webkit-transform: scale(0) } 40% { -webkit-transform: scale(1.0) }  }  @keyframes sk-bouncedelay { 0%, 80%, 100% { -webkit-transform: scale(0); transform: scale(0); } 40% { -webkit-transform: scale(1.0);  transform: scale(1.0);  }  }")}},
{key:"showLoaderAnim",value:function(){this.sa.appendChild(this.Gb)}},{key:"hideLoaderAnim",value:function(){if(this.Gb&&null!==this.Gb.parentNode)this.sa.removeChild(this.Gb);else{var a=document.querySelector(".ob_sf_loader");a&&null!==a.parentNode&&a.parentNode.removeChild(a)}}},{key:"afterRender",value:function(a){var b=OBR.pa.we(a);if(b.Qc()){var c=OBR.b.v(a);OBR.g.log("feed afterRender, idx: "+a);parseInt(b.ne(),10)===this.$&&this.hideLoaderAnim();a=this.buildIntersectionObserverObject(c);(new OBR.Cb(a)).observe();
this._initInteractionLayer(b)}}},{key:"buildIntersectionObserverObject",value:function(a){return{element:a,callback:this.fireLastWidgetExposeEvent.bind(this),threshold:[0],unobserve:!0,callbackParams:[a.getAttribute("id").substr(16)]}}},{key:"fireLastWidgetExposeEvent",value:function(a){if(!this.vc&&(this.Fj=!0,!this.isNextChunkLoaded(OBR.i[a].ne(),this.$,this.hg)))for(a=0;a<this.hg;a+=1)if(0<this.Eb.length)if(this.isJokerPosition())this.createNextJoker();else{this.wc=this.getNextWidget();if(null===
this.wc){0<a&&this.showLoaderAnim();break}this.createWidgetContainer()}}},{key:"isJokerPosition",value:function(){return!!this.ra[this.$+1]}},{key:"createNextJoker",value:function(){this.$+=1;this.createJokerContainer(this.ra[this.$]);delete this.ra[this.$]}},{key:"isNextChunkLoaded",value:function(a,b,c){return Math.floor((b-1)/c)>Math.floor((a-1)/c)}},{key:"getNextWidget",value:function(){if(!this.vc){var a=this.promoteContent();return a.value?a.value.id:null}}},{key:"promoteContent",value:function(){var a=
this.getNext(this.Eb,this.Pd);this.Pd=a.idx;return 0===this.Pd&&(this.eg++,0<this.gg&&this.eg>this.gg)?(this.stopInfiniteScroll(),{}):a}},{key:"getNext",value:function(a,b){b=0<=b&&b<a.length-1?b+1:0;return{value:a[b],idx:b}}},{key:"createRemainingJokers",value:function(){for(var a in this.ra)this.ra.hasOwnProperty(a)&&this.createJokerContainer(this.ra[a])}},{key:"stopInfiniteScroll",value:function(a){if(!a||a.Qc())OBR.g.log("Stop Infinite scrolling"),this.vc=!0,this.createRemainingJokers(),this.hideLoaderAnim()}},
{key:"_initInteractionLayer",value:function(a){var b=!0===a.e("oo",!1),c=a.f("interactionLayerEnabled",!1);if(!b&&c)return new OBR.Da(a)}}]);return c}();
var z={LIKE:{ID:1,Note:0},DISLIKE:{ID:2,Note:0},UNDO_DISLIKE:{ID:3,Note:0},UNDO_LIKE:{ID:4,Note:0},STASH:{ID:5,Note:0},UNDO_STASH:{ID:6,Note:0},SHARE:{FACEBOOK:{ID:7,Note:100},TWITTER:{ID:7,Note:101},MAIL:{ID:7,Note:102},CLIPBOARD:{ID:7,Note:103},MOBILE_NATIVE:{ID:7,Note:104}},REPORTS:{UNDO:{ID:9,Note:0},INAPPROPRIATE:{ID:8,Note:150},MISLEADING:{ID:8,Note:151},FAKE_NEWS:{ID:8,Note:153},SCAM:{ID:8,Note:154},OTHER:{ID:8,Note:152}}},A=function(){function c(){y(this,c);this.Od=OBR.c.Wc+"logger/v1/userActions/";
this.Eo=(new Date).getTime()}t(c,[{key:"fireDataBIReport",value:function(a,b,c){a={at:a.ID,an:a.Note,uuid:c.e("lsd",""),sid:c.e("sid",""),pid:c.e("pid",""),docURL:c.X(),wId:c.r(),seId:c.e("req_id",-1)+this.Eo,reqId:c.e("req_id","-1"),rec_en_did:b.rec_en_did,ttid:b.ttid};"undefined"!==typeof b.pc_id&&"undefined"!==typeof b.pc_cmp_id&&(a.adId=b.pc_id,a.cId=b.pc_cmp_id);this._sendReport(a)}},{key:"getExtendedDataFromRecLink",value:function(a){a=a.querySelector("[data-event]");return this.getExtendedData(a)}},
{key:"getExtendedData",value:function(a){var b={};a&&(a=OBR.b.N(a,"data-event"))&&(b=JSON.parse(a));return b}},{key:"_sendReport",value:function(a){OBR.ua.Be()?OBR.ua.Xc(this.Od,a,OBR.b.Ia):(a=OBR.b.M(0,this._prepareGetURL(a),!0,!0),OBR.b.O(a))}},{key:"_prepareGetURL",value:function(a){var b=this.Od,b=b+("?eventId="+a.eventId),b=b+("&pId="+a.pId),b=b+("&sId="+a.sId),b=b+("&wId="+a.wId),b=b+("&uuid="+a.uuid),b=b+("&pvId="+a.pvId),b=b+("&reqId="+a.reqId),b=b+("&did="+a.did),b=b+("&idx="+a.idx),b=b+
(a.ttid?"&ttid="+a.ttid:""),b=b+(a.targetDid?"&targetDid="+a.targetDid:"");return b+=a.eventData?"&eventData="+a.eventData:""}}]);return c}(),H=function(){function c(){y(this,c);this.Tf="OB-INTERACTION-STASH";this.ei=[];this.ki=[]}t(c,[{key:"addToStash",value:function(a){this._stash(a)}},{key:"removeFromStash",value:function(a){a=OBR.b.N(a,"data-code");this._unstash(a)}},{key:"removeFromStashByHashCode",value:function(a){this._unstash(a)}},{key:"isStashed",value:function(a){a=OBR.b.N(a,"data-code");
return this._getStorage().hasOwnProperty(a)}},{key:"getAllStashedItems",value:function(){return this._getStorage()}},{key:"observe",value:function(a,b){this.ei.push(a);this.ki.push(b)}},{key:"_getChangedItemHash",value:function(a,b,c){var d=b;2===a&&(a=[d,c],c=a[0],d=a[1]);return c.Uq.filter(function(a){return!d.hasOwnProperty(a)})}},{key:"_extractMetadata",value:function(a){var b={};b.url=OBR.b.N(a,"href");b.img=this._getData(a,".ob-rec-image","src");b.text=this._getData(a,".ob-rec-text","title");
b.source=this._getData(a,".ob-rec-source","innerText",!0);return{hash:OBR.b.N(a,"data-code"),data:b}}},{key:"_getData",value:function(a,b,c,d){var f=null;d=d||!1;(a=a.querySelector(b))&&(f=d&&c in a?a[c]:OBR.b.N(a,c));return f}},{key:"_stash",value:function(a){var b=OBR.b.N(a,"data-code");OBR.Da.toggleStash(b);a=this._extractMetadata(a);this._addDataToStorage(a)}},{key:"_unstash",value:function(a){OBR.Da.toggleStash(a);this._removeDataFromStorage(a)}},{key:"_getStorage",value:function(){var a=OBR.b.ob(this.Tf)||
'{"order":[]}';return JSON.parse(a)}},{key:"_setStorage",value:function(a){OBR.b.hd(this.Tf,JSON.stringify(a))}},{key:"_addDataToStorage",value:function(a){var b=this._getStorage(),c=a.hash;b[c]=a.data;b.order.push(c);this._setStorage(b);this._notifyOnAdd(a)}},{key:"_notifyOnAdd",value:function(a){this.ei.forEach(function(b){b(a)})}},{key:"_removeDataFromStorage",value:function(a){var b=this._getStorage();delete b[a];var c=b.order.indexOf(a);b.order.splice(c,1);this._setStorage(b);this._notifyOnRemove(a,
c)}},{key:"_notifyOnRemove",value:function(a,b){this.ki.forEach(function(c){c(a,b)})}}]);return c}(),U=function(){function c(a,b){y(this,c);this.s=b;var e=a.querySelector(".ob-dynamic-rec-link"),d=a.querySelector(".ob-intr-report"),f=a.querySelector(".ob-intr-report .obr-intr-icon-x"),h=a.querySelector(".ob-intr-report-menu"),g=h.querySelector("li:last-child"),k=h.querySelectorAll("li[data-report-type]");this._blockLandingPageRedirect(d);this._bindReportActionButtonClicks(k,g,e);this._bindReportShowButton(f,
e,h,g,a)}t(c,[{key:"_blockLandingPageRedirect",value:function(a){a.addEventListener("click",function(a){a.preventDefault();a.stopPropagation();return!1})}},{key:"_bindReportActionButtonClicks",value:function(a,b,c){var d=this,f=c.querySelector('[data-action="like"]');a.forEach(function(a){a.addEventListener("click",function(){var g=OBR.b.N(a,"data-report-type"),g=z.REPORTS[g],k=T.getExtendedDataFromRecLink(c);T.fireDataBIReport(g,k,d.s);d._disableRecommendation(c);OBR.b.J(f,"ob-icon-on");OBR.b.D(c.parentElement,
"ob-intr-disabled");b.click()})})}},{key:"_disableRecommendation",value:function(a){var b=this._insertInteractionOverlay(a,"ob-intr-overlay ob-intr-overlay-disabled");this._blockLandingPageRedirect(b);this._insertUndoButton(a,b)}},{key:"_insertUndoButton",value:function(a,b){var c=this;b.insertAdjacentHTML("afterbegin",'<a href="#" class="ob-intr-undo">Undo</a>');var d=b.querySelector("a"),f=T.getExtendedDataFromRecLink(a);d.addEventListener("click",function(){T.fireDataBIReport(z.REPORTS.UNDO,f,
c.s);OBR.b.cd(b);OBR.b.J(a.parentElement,"ob-intr-disabled");return!1})}},{key:"_insertInteractionOverlay",value:function(a,b){if(a&&a.insertAdjacentHTML)return a.insertAdjacentHTML("beforebegin",'<div class="'+(b||"ob-intr-overlay")+'"></div>'),a.previousSibling}},{key:"_bindReportShowButton",value:function(a,b,c,d,f){var h=this;a.addEventListener("click",function(){var a=h._insertInteractionOverlay(b),k=h._getCloseReportOverlayFn(a,c);a.addEventListener("click",k);d.addEventListener("click",k);
OBR.b.D(c,"ob-intr-report-on");h._setReportMenuMaxWidth(f)})}},{key:"_getCloseReportOverlayFn",value:function(a,b){return function(){OBR.b.cd(a);OBR.b.J(b,"ob-intr-report-on")}}},{key:"_setReportMenuMaxWidth",value:function(a){var b=a.children[0];(a=a.querySelector(".ob-intr-report-menu"))&&(0<a.offsetWidth&&0<a.offsetHeight)&&(a.style.maxWidth=b.clientWidth-10+"px")}}]);return c}(),T=new A,V=new H;
OBR.Da=OBR.Da||function(){function c(a){y(this,c);this.s=a;this.uf=null;this.kb=OBR.b.v(this.s.I());this.initWidget()}t(c,null,[{key:"staticConstructor",value:function(){var a=document.querySelectorAll(".ob-smartfeed-wrapper");a&&a.forEach(function(a){OBR.Da.NavigatorShareApiSupported||OBR.b.D(a,"ob-no-share-api");OBR.c.Q&&OBR.b.mn()&&OBR.b.D(a,"ob-mobile-touch")})}},{key:"toggleStash",value:function(a){(a=document.querySelectorAll('.OUTBRAIN a[data-code="'+a+'"] .ob-rec-interaction .ob-intr-save'))&&
a.forEach(function(a){OBR.b.kc(a,"ob-icon-on");OBR.b.kc(a,"ob-icon-off")})}},{key:"ResizeObserverApiSupported",get:function(){return!!window.ResizeObserver}},{key:"NavigatorShareApiSupported",get:function(){return!!navigator.share}}]);t(c,[{key:"initWidget",value:function(){var a=this;this.kb&&(this.rk=this.kb.querySelectorAll(".ob-dynamic-rec-container"),this.rk.forEach(function(b){a.hasInteractionLayer(b)&&(a.setRecWidthAndLabels(b),a.setShareMenuPosition(b),a.observeResize(b),a.bindClickEvent(b),
a.initReportMenu(b),a.initStashBtnState(b))}),this.s.Ge()?this.initStash():this.qg=this.kb.parentElement.querySelector(".ob-stash-count"))}},{key:"initStashBtnState",value:function(a){var b=a.querySelector(".ob-dynamic-rec-link ");this.injectStashHashAttribute(b);V.isStashed(b)&&(a=a.querySelector(".ob-intr-save"),this.toggleBtnClasses(a))}},{key:"injectStashHashAttribute",value:function(a){var b=a.querySelector("[data-event]");b&&(b=OBR.b.N(b,"data-event"))&&b.length&&(b=JSON.parse(b),OBR.b.ha(a,
"data-code",b.rec_en_did))}},{key:"initReportMenu",value:function(a){this.Ii=new U(a,this.s)}},{key:"bindClickEvent",value:function(a){var b=this,c=a.querySelector("a.ob-dynamic-rec-link");a.querySelector(".ob-rec-interaction").addEventListener("click",function(a){var f=a.target;OBR.b.Sm(f)&&f.parentElement&&(f=f.parentElement);OBR.b.vh(f,"ob-intr-icon")&&b.handleClickEvent(c,f);a.preventDefault();a.stopPropagation();return!1})}},{key:"observeResize",value:function(a){var b=this,c=OBR.Jg(function(){b.setRecWidthAndLabels(a);
b.setShareMenuPosition(a);b.setReportMenuMaxWidth(a)},250);OBR.Da.ResizeObserverApiSupported?(new window.ResizeObserver(c)).observe(a):window.addEventListener("resize",c)}},{key:"setShareMenuPosition",value:function(a){var b="50%",c=a.querySelector('.ob-intr-container [data-action="share"]'),d=a.querySelector(".ob-intr-share-menu");350<=a.clientWidth&&(b=c.getBoundingClientRect(),a=d.parentElement.getBoundingClientRect(),b=b.x+b.width/2,b=Math.round(b-a.x),b+="px");d.style.left=b}},{key:"setRecWidthAndLabels",
value:function(a){var b=a.querySelector(".ob-intr-container");234<=a.clientWidth?OBR.b.D(b,"ob-intr-med"):OBR.b.J(b,"ob-intr-med");500<=a.clientWidth?OBR.b.D(b,"ob-intr-wide"):OBR.b.J(b,"ob-intr-wide")}},{key:"hasInteractionLayer",value:function(a){return!!a.querySelector(".ob-intr-container")}},{key:"setReportMenuMaxWidth",value:function(a){var b=a.children[0];(a=a.querySelector(".ob-intr-report-menu"))&&(0<a.offsetWidth&&0<a.offsetHeight)&&(a.style.maxWidth=b.clientWidth-10+"px")}},{key:"handleClickEvent",
value:function(a,b){var c=a.parentElement,d=OBR.b.N(b,"data-action"),f=T.getExtendedDataFromRecLink(a);switch(d){case "like":this.handleLikeClick(f,b,c);c=a.querySelector('[data-action="dislike"]');OBR.b.J(c,"ob-icon-on");break;case "dislike":this.handleDislikeClick(f,b,c);c=a.querySelector('[data-action="like"]');OBR.b.J(c,"ob-icon-on");break;case "save":this.handleStashClick(f,a,b);break;case "share":this.handleShareClick(a,b)}}},{key:"toggleBtnClasses",value:function(a){a&&(OBR.b.kc(a,"ob-icon-on"),
OBR.b.kc(a,"ob-icon-off"))}},{key:"getNextActionType",value:function(a,b,c){var d=a.ob_actionType,d=d?d===b?c:b:OBR.b.vh(a,"ob-icon-on")?c:b;return a.ob_actionType=d}},{key:"handleLikeClick",value:function(a,b){this.toggleBtnClasses(b);if(a){var c=this.getNextActionType(b,z.LIKE,z.UNDO_LIKE);T.fireDataBIReport(c,a,this.s)}}},{key:"handleDislikeClick",value:function(a,b){var c=this.getNextActionType(b,z.DISLIKE,z.UNDO_DISLIKE);this.toggleBtnClasses(b);a&&T.fireDataBIReport(c,a,this.s)}},{key:"handleStashClick",
value:function(a,b,c){c=this.getNextActionType(c,z.STASH,z.UNDO_STASH);T.fireDataBIReport(c,a,this.s);this.updateStashState(b)}},{key:"updateStashState",value:function(a){var b=V.isStashed(a)?"removeFromStash":"addToStash";V[b](a);this.updateStashCounter()}},{key:"handleShareClick",value:function(a,b){var c=this.getShareUrl(a),d=a.parentElement.querySelector(".ob-intr-share-menu"),f=this.insertInteractionOverlay(a);OBR.b.D(b,"ob-icon-on");OBR.b.D(d,"ob-intr-on");var h=this.getCloseOverlayFn(a,b);
this.bindShareMenuEvents(d,c,h);f.addEventListener("click",h)}},{key:"nativeShareApiHandler",value:function(a){a=navigator.share({url:a});a.then(function(){console.log("navigator.share completed")});a["catch"](function(a){console.log(a)})}},{key:"getShareUrl",value:function(a){if(!OBR.b.Vb(a))return encodeURIComponent(OBR.b.N(a,"href"))}},{key:"bindShareMenuEvents",value:function(a,b,c){this.bindFacebookButtonClick.apply(this,arguments);this.bindTweetButtonClick.apply(this,arguments);this.bindMailtoButtonClick.apply(this,
arguments);this.bindCopyToClipboardButtonClick.apply(this,arguments);this.bindShareApiButtonClick.apply(this,arguments)}},{key:"commonShareMenuButtonClickHandler",value:function(a,b,c,d){d&&(c=T.getExtendedData(c.parentElement),T.fireDataBIReport(d,c,this.s));b();a.preventDefault();a.stopPropagation();return!1}},{key:"bindShareApiButtonClick",value:function(a,b,c){var d=this;if(OBR.Da.NavigatorShareApiSupported){var f=a.querySelector(".ob-intr-share-native").parentElement;b=OBR.b.N(a,"data-orig-url");
this.bindClickOnce(f,function(f){d.nativeShareApiHandler(decodeURIComponent(b));return d.commonShareMenuButtonClickHandler(f,c,a,z.SHARE.MOBILE_NATIVE)})}}},{key:"bindCopyToClipboardButtonClick",value:function(a,b,c){var d=this,f=a.querySelector(".ob-intr-share-url");this.bindClickOnce(f,function(f){OBR.Ag.copy(decodeURIComponent(b));return d.commonShareMenuButtonClickHandler(f,c,a,z.SHARE.CLIPBOARD)})}},{key:"bindMailtoButtonClick",value:function(a,b,c){var d=this,f=a.querySelector(".ob-intr-share-mail");
this.bindClickOnce(f,function(f){window.location.href="mailto:?body="+b;return d.commonShareMenuButtonClickHandler(f,c,a,z.SHARE.MAIL)})}},{key:"bindTweetButtonClick",value:function(a,b,c){var d=this,f="https://twitter.com/share?url="+b;b=a.querySelector(".ob-intr-share-twtr");this.bindClickOnce(b,function(b){window.open(f);return d.commonShareMenuButtonClickHandler(b,c,a,z.SHARE.TWITTER)})}},{key:"bindFacebookButtonClick",value:function(a,b,c){var d=this;b=OBR.b.N(a,"data-orig-url");var f="https://www.facebook.com/sharer.php?u="+
b;b=a.querySelector(".ob-intr-share-fb");this.bindClickOnce(b,function(b){window.open(f);return d.commonShareMenuButtonClickHandler(b,c,a,z.SHARE.FACEBOOK)})}},{key:"bindClickOnce",value:function(a,b){OBR.b.N(a,"data-is-bound")||(a.addEventListener("click",b),OBR.b.ha(a,"data-is-bound",1))}},{key:"getCloseOverlayFn",value:function(a,b){return function(){OBR.b.cd(a.previousSibling);OBR.b.J(b,"ob-icon-on");OBR.b.J(a.parentElement.querySelector(".ob-intr-share-menu"),"ob-intr-on")}}},{key:"insertInteractionOverlay",
value:function(a,b){if(a&&a.insertAdjacentHTML)return a.insertAdjacentHTML("beforebegin",'<div class="'+(b||"ob-intr-overlay")+'"></div>'),a.previousSibling}},{key:"initStash",value:function(){var a=this;this.injectStashContainer();var b=this.kb.querySelector("a.ob-btn-stash"),c=this.kb.querySelector(".ob-intr-stash");b.addEventListener("click",function(d){OBR.b.kc(b,"ob-btn-stash-close");a.toggleStashedItems(c);d.preventDefault();d.stopPropagation();return!1})}},{key:"injectStashContainer",value:function(){var a=
'<div class="ob-intr-stash">\n        <a href="#" class="ob-btn-stash" title="Open/Hide stashed recommendations"><span class="ob-stash-count">'+V.getAllStashedItems().order.length+'</span></a>\n        <div class="ob-stash-content" style="display:none;">\n          <span class="ob-stash-head">Your saved stories</span>\n          <div class="ob-intr-stash-scroll"></div>\n        </div>\n      </div>',b=this.kb.querySelector(".ob-widget-items-container");b.insertAdjacentHTML("beforebegin",a);this.qg=
b.parentElement.querySelector(".ob-stash-count")}},{key:"updateStashCounter",value:function(){var a=V.getAllStashedItems().order.length;this.qg.innerText=a}},{key:"toggleStashedItems",value:function(a){var b=this;this.loadStashRenderer().yb(function(){b.uf||(b.uf=new OBR.tc(a,V));b.uf.toggle()})}},{key:"loadStashRenderer",value:function(){var a=new OBR.hb;OBR.tc?setTimeout(function(){a.Ta()},0):OBR.d.q(OBR.d.h.Cd,function(){a.Ta()},this);return a}}]);return c}();OBR.ic=OBR.ic||new OBR.Fd;OBR.d.w(OBR.d.h.Bd);
OBR.Da.staticConstructor();
